=== Introduction

There are two main parts of Spring XD that can be configured, servers and modules.  

The servers (`xd-singlenode`, `xd-admin`, `xd-container`) are http://projects.spring.io/spring-boot/[Spring Boot] applications and are configured as described in the http://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/htmlsingle/[Spring Boot Reference documentation].  In the most simple case this means editing values in the YAML based configuration file `servers.yml`.  The values in this configuration file will overwrite the values in the default https://github.com/spring-projects/spring-xd/blob/master/spring-xd-dirt/src/main/resources/application.yml[application.yml] file that is embedded in the XD jar.

NOTE: The use of YAML is an alternative to using property files. YAML is a superset of JSON, and as such is a very convenient format for specifying hierarchical configuration data.

For modules, each module has its own configuration file located in its own directory, for example `source/http/http.properties`.  Shared configuration values for modules can be placed in a common `modules.yml` file.  

For both server and module configuration, you can have environment specific settings through the use of application profiles and the ability to override values in files by setting OS environment variables.  

In this section we will walk though how to configure servers and modules.

=== Server Configuration

The startup scripts for `xd-singlenode`, `xd-admin`, and `xd-container` will by default look for the file `$XD_HOME\config\servers.yml` as a source of externalized configuration information.  

The location and name of this resourse can be changed by using the environment variables `XD_CONFIG_LOCATION` and `XD_CONFIG_NAME`.  The start up script takes the value of these environment variables to set the Spring Boot properties `spring.config.location` and `spring.config.name`.  Note, that for `XD_CONFIG_LOCATION` you can reference any http://docs.spring.io/spring/docs/4.0.3.RELEASE/spring-framework-reference/htmlsingle/#resources[Spring Resource] implementation, most commonly denoted using the prefixes `classpath:`, `file:` and `http:`.

It is common to keep your server configuration separate form the installation directory of XD itself.  To do this, here is an example environment variable setting 

[source,bash]
----
export XD_CONFIG_LOCATION=file:/xd/config/
export XD_CONFIG_NAME=region1-servers
----

==== Profile support

Profiles provide a way to segregate parts of your application configuration and change their availability and/or values based on the environment.  This lets you have different configuration settings for `qa` and `prod` environments and to easily switch between them.

To activate a profile, set the OS environment variable `SPRING_PROFILES_ACTIVE` to a comma delimited list of profile names.  The server looks to load profile specific variants of the `servers.yml` file based on the naming convention `servers-{profile}.yml`.  For example, if `SPRING_PROFILES_ACTIVE=prod` the following files would be searched for in the following order.

. `XD_CONFIG_LOCATION/servers-prod.yml`
. `XD_CONFIG_LOCATION/servers.yml`

You may also put multiple profile specific configuration in a single `servers.yml` file by using the key `spring.profiles` in different sections of the configuration file.  See http://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/htmlsingle/#boot-features-external-config-multi-profile-yaml[Multi-profile YAML documents] for more information.

==== Database Configuration

Spring XD saves the state of the batch job workflows in a relational database.  When running `xd-singlenode` a embedded HSQLDB database is run.  When running in distributed mode a standalone HSQLDB instance can be used, the startup script `hsqldb-server` is in is provided the installation directory under the folder 'hsqldb/bin'.  It is recommended to use HSQLDB only for development and learning. 

When deploying in a production environment, you will need to select another database.  Spring XD is actively tested on MySql (Version: 5.1.23) and Postgres (Version 9.2-1002).  All batch workflow tables are automatically created, if they do not exist, for HSQLDB, MySQL and Postgres.  The JDBC driver jars for the HSQLDB, MySql, and Postgres are already on the XD classpath.

The provided configuration file `servers.yml` located in `$XD_HOME\config` has commented out configuration for some commonly used databases.  You can use these as a basis to support your database environment.

NOTE: Until full schema support is added for Oracle, Sybase and other database, you will need to put a .jar file in the `xd/lib` directory that contains the equivalent functionality as these https://github.com/spring-projects/spring-xd/tree/master/spring-xd-batch/src/main/resources/org/springframework/xd/batch/schema[DDL scripts].  

NOTE: There was a schema change in version 1.0 RC1.  Use or adapt the the https://gist.github.com/ilayaperumalg/3f379eb7f4527f6f6da4[sample migration class] to update your schema.


===== HSQLDB 

When in distributed mode and you want to use HSQLDB, you need to change the value of `spring.datasource` properties.  As an example, 

[source,yaml]
----
hsql:
 server:
   host: localhost
   port: 9102
   dbname: xdjob
spring:
   datasource:
   url: jdbc:hsqldb:hsql://${hsql.server.host:localhost}:${hsql.server.port:9101}/${hsql.server.dbname:xdjob}
   username: sa
   password:
   driverClassName: org.hsqldb.jdbc.JDBCDriver
----

The properties under `hsql.server` are substituted in the `spring.datasource.url` property value.  This lets you create short variants of existing Spring Boot properties.  Using this style, you can override the value of these configuration variables by setting an OS environment variable, such as `xd_server_host`.  Alternatively, you can not use any placeholders and set `spring.datasource.url` directly to known values. 

===== MySQL

When in distributed mode and you want to use MySQL, you need to change the value of `spring.datasource.*` properties.  As an example, 

[source,yaml]
----
spring:
 datasource:
 url: jdbc:mysql://yourDBhost:3306/yourDB
 username: yourUsername
 password: yourPassword
 driverClassName: com.mysql.jdbc.Driver
----

To override these settings set an OS environment variable such as `spring_datasource_url` to the value you require.


===== PostgreSQL

When in distributed mode and you want to use PostgreSQL, you need to change the value of `spring.datasource.*` properties.  As an example, 

[source,yaml]
----
spring:
  datasource:
    url: jdbc:postgresql://yourDBhost:5432/yourDB
    username: yourUsername
    password: yourPassword
    driverClassName: org.postgresql.Driver
----

To override these settings set an OS environment variable such as `spring_datasource_url` to the value you require.

==== Redis

If you want to use Redis for analytics or data transport you should set the host and port of the Redis server.

[source,yaml]
----
spring:
  redis:
   port: 6379
   host: localhost
----

To override these settings set an OS environment variable such as `spring_redis_port` to the value you require.

==== RabbitMQ

If you want to use RabbitMQ as a data transport use the following configuration setting

[source,yaml]
----
spring:
  rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
   virtual_host: /
----

To override these settings set an OS environment variable such as `spring_rabbitmq_host` to the value you require.


In addition, the following default settings for the rabbit message bus can be modified in `servers.yml`...

[source,yaml]
----
  messagebus:
    rabbit:
      default:
        ackMode:                   AUTO  # <1>
        backOffInitialInterval:    1000  # <2>
        backOffMaxInterval:        10000 # <3>
        backOffMultiplier:         2.0   # <4>
        concurrency:               1     # <5>
        maxAttempts:               3     # <6>
        maxConcurrency:            1     # <7>
        prefix:                    xdbus. # <8>
        prefetch:                  1     # <9>
        replyHeaderPatterns:       STANDARD_REPLY_HEADERS,*   # <10>
        requestHeaderPatterns:     STANDARD_REQUEST_HEADERS,* # <11>
        requeue:                   true  # <12>
        transacted:                false # <13>
        txSize:                    1     # <14>
----

<1> AUTO (container acks), NONE (broker acks), MANUAL (consumer acks). Upper case only. Note: MANUAL requires specialized code in the consuming module and is unlikely to be used in an XD application. For more information, see http://docs.spring.io/spring-integration/reference/html/amqp.html#amqp-inbound-ack

<2> The time in milliseconds before retrying a failed message delivery

<3> The maximum time (ms) to wait between retries

<4> The back off multiplier (previous interval x multiplier = next interval)

<5> The minimum number of consumer threads receiving messages for a module

<6> The maximum number of delivery attempts

<7> The maximum number of consumer threads receiving messages for a module

<8> A prefix applied to all queues, exchanges so that policies (HA etc) can be applied

<9> The number of messages to prefetch for each consumer

<10> Determines which request headers will be transported

<11> Determines which reply headers will be transported

<12> Whether rejected messages will be requeued by default

<13> Whether the channel is to be transacted

<14> The number of messages to process between acks (when ack mode is AUTO).

==== Admin Server HTTP Port

The default HTTP port of the `xd-admin` server is 9393.  To change the value use the following configuration setting

[source,yaml]
----
server:
  port: 9876
----

==== Management Port

The XD servers provide general http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints[health] and JMX exported http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-jolokia[management] endpoints via Jolokia.  

By default the management and health endpoints are available on port 9393.  To change the value of the port use the following configuration setting.

[source,yaml]
----
management:
  port: 9876
----

You can also disable http management endpoints by setting the port value to -1.

By default JMX MBeans are exported.  You can disable JMX by setting `spring.jmx.enabled=false`.

The section on http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-monitoring[Monitoring and management over HTTP] provides details on how to configure these endpoint.

==== Local transport

Local transport uses a http://docs.spring.io/spring-integration/docs/latest-ga/api/org/springframework/integration/channel/QueueChannel.html[QueueChannel] to pass data between modules.  There are a few properties you can configure on the QueueChannel

* `xd.local.transport.named.queueSize` - The capacity of the queue, the default value is `Integer.MAX_VALUE`
* `xd.local.transport.named.polling` - Messages that are buffered in a QueueChannel need to be polled to be consumed.  This property controls the fixed rate at which polling occurs.  The default value is 1000 ms.

=== Module Configuration

Modules are configured by placing property files in a nested directory structure based on their type and name.  The root of the nested directory structure is by default `XD_HOME/config/modules`.  This location can be customized by setting the OS environment variable `XD_MODULE_CONFIG_LOCATION`, similar to how the environment variable `XD_CONFIG_LOCATION` is used for configuring the server.

NOTE: The `XD_MODULE_CONFIG_LOCATION` can reference any http://docs.spring.io/spring/docs/4.0.3.RELEASE/spring-framework-reference/htmlsingle/#resources[Spring Resource] implementation, most commonly denoted using the prefixes `classpath:`, `file:` and `http:`.

As an example, if you wanted to configure the twittersearch module, you would create a file 
----
XD_MODULE_CONFIG_LOCATION\source\twittersearch\twittersearch.properties
----

and the contents of that file would be property names such as `consumerKey` and `consumerSecret`.

NOTE: You *do not* need to prefix these property names with a `source.twittersearch` prefix.

You can override the values in the module property file in various ways.  The following sources of properties are considered in the following order.

. Properties specified in the stream or job `DSL` definition
. Java System Properties
. OS environment variables.
. `XD_MODULE_CONFIG_LOCATION\<type>\<name>\<name>.properties` (including profile variants)
. Default values specified in module metadata (if available).

Values in `XD_MODULE_CONFIG_LOCATION\<type>\<name>\<name>.properties` can be property placeholder references to keys defined in another resource location.  By default the resource is the file `XD_MODULE_CONFIG_LOCATION\modules.yml`.  You can customize the name of the resource by using setting the OS environment variable `XD_MODULE_CONFIG_NAME` before running a server startup script.

The `modules.yml` file can be used to specify the values of keys that should be shared across different modules.  For example, it is common to use the same twitter developer credentials in both the twittersearch and twitterstream modules.  To avoid repeating the same credentials in two property files, you can use the following setup.

`modules.yml` contains

[source,yaml]
----
sharedConsumerKey: alsdjfqwopieur
sharedConsumerSecret: pqwieouralsdjkqwpo
sharedAccessToken: llixzchvpiawued
sharedAccessTokenSecret: ewoqirudhdsldke
----

and `XD_MODULE_CONFIG_LOCATION\source\twitterstream\twitterstream.properties` contains

----
consumerKey=${sharedConsumerKey}
consumerSecret=${sharedConsumerSecret}
accessToken=${sharedAccessToken}
accessTokenSecret=${sharedAccessTokenSecret}
----

and `XD_MODULE_CONFIG_LOCATION\source\twittersearch\twittersearch.properties` contains
----
consumerKey=${sharedConsumerKey}
consumerSecret=${sharedConsumerSecret}
----

==== Profiles

When resolving property file names, the server will look to load profile specific variants based on the naming convention `<name>-{profile}.properties`.  For example, if given the OS environment variable `spring_profiles_active=default,qa` the following configuration file names for the twittersearch module would be searched in this order

. `XD_MODULE_CONFIG_LOCATION\source\twittersearch\twittersearch.properties`
. `XD_MODULE_CONFIG_LOCATION\source\twittersearch\twittersearch-default.properties`
. `XD_MODULE_CONFIG_LOCATION\source\twittersearch\twittersearch-qa.properties`

Also, the shared module configuration file is refernced using profile variants, so given the OS environment variable `spring_profiles_active=default,qa` the following shared module configuration files would be searched for in this order

. `XD_MODULE_CONFIG_LOCATION\modules.yml`
. `XD_MODULE_CONFIG_LOCATION\modules-default.yml`
. `XD_MODULE_CONFIG_LOCATION\modules-qa.yml`

==== Batch Jobs or modules accessing JDBC

Another common case is access to a relational database from a job or the JDBC Sink module.

As an example, to provide the properties for the batch job `jdbchdfs` the file `XD_MODULE_CONFIG_LOCATION\job\jdbchdfs\jdbchdfs.properites` should contain
----
driverClass=org.hsqldb.jdbc.JDBCDriver
url=jdbc:hsqldb:mem:xd
username=sa
password=
----

A property file with the same keys, but likely different values would be located in `XD_MODULE_CONFIG_LOCATION\sink\jdbc\jdbc.properites`.

