=== Instructions

Here are some useful steps to build and run Spring XD.

To build all sub-projects and run tests for Spring XD:

----
./gradlew build
----

To build and bundle the distribution of Spring XD

----
./gradlew dist
----

The above gradle task creates spring-xd-<version>.zip binary distribution archive and spring-xd-<version>-docs.zip documentation archive files under 'build/distributions'. This will also create a 'build/dist/spring-xd' directory which is the expanded version of the binary distribution archive.

To just create the Spring XD expanded binary distribution directory

----
./gradlew copyInstall
----

The above gradle task creates the distribution directory under 'build/dist/spring-xd'.

Once the binary distribution directory is created, please refer to link:https://github.com/SpringSource/spring-xd/wiki/Getting-Started[Getting Started] on how to run Spring XD.

=== IDE support

If you would like to work with the Spring XD code in your IDE, please use the following project generation depending on the IDE you use:

For Eclipse/Spring Tool Suite

----
./gradlew eclipse
----

For IntelliJ IDEA
----
./gradlew idea
----

Then just import the project as an existing project.

=== Running JavaScript UI Tests

In order to run the UI tests, `phantomjs` must be installed on your system. On a Mac using brew execute:
----
brew install phantomjs
----

Alternatively, you can also install `phantomjs` using the Node Package Manager:
----
npm install -g phantomjs
----

Afterwards, execute:

----
./gradlew jsTest
----

As a result you should see console output similar to the following:

----
:spring-xd-ui:jsTest
Opening: http://localhost:9393/admin-ui/test/SpecRunnerPhantomJS.html
Starting...

Finished
-----------------
8 specs, 0 failures in 0.073s.

ConsoleReporter finished: success
Stopped the SingleNode server.

BUILD SUCCESSFUL
----