=== Requirements

{asciidoctor-version}
To get started, make sure your system has as a minimum  http://www.oracle.com/technetwork/java/javase/downloads/[*Java JDK 6*] or newer installed. *Java JDK 7* is recommended.

=== Download Spring XD

Download http://www.springframework.org[spring-xd-1.0-M1.zip] (TODO)

Unzip the distribution. This will yield the installation directory *spring-xd*. All the commands below are executed from this directory, so change into it before proceeding

[source,sh]
----
$ cd spring-xd
----

=== Install Spring XD

Spring XD can be run in two different modes. There's a single-node runtime option for testing and development, and there's a distributed runtime which supports distribution of processing tasks across multiple nodes. This document will get you up and running quickly with a single-node runtime. See link:Running-Distributed-Mode[Running Distributed Mode] for details on setting up a distributed runtime.


=== Start the Runtime

The single node option is the easiest to get started with. It runs everything you need in a single process. To start it, you just need to run the following command

[source,sh]
----
xd/bin>$ ./xd-singlenode
----

You should then be able to start using Spring XD.

=== Create a Stream
In Spring XD, a basic stream defines the ingestion of event driven data from a source to a sink that passes through any number of processors. Create a new stream by posting the stream definition to a REST endpoint.  Stream defintions are built from a simple DSL. For example, execute:

  $ curl -d "time | log" http://localhost:8080/streams/ticktock

This defines a stream named `ticktock` based off the DSL expression `time | log`.  The DSL uses the "pipe" symbol `|`, to connect a source to a sink. The stream server finds the `time` and `log` definitions in the modules directory and uses them to setup the stream.  In this simple example, the time source simply sends the current time as a message each second, and the log sink outputs it using the logging framework.

  processing module 'Module [name=log, type=sink]' from group 'ticktock' with index: 1
  processing module 'Module [name=time, type=source]' from group 'ticktock' with index: 0
  17:26:18,774  WARN ThreadPoolTaskScheduler-1 logger.ticktock:141 - Thu May 23 17:26:18 EDT 2013

=== Explore Spring XD
Learn about the modules available in Spring XD in the link:Sources[Sources], link:Processors[Processors], and link:Sinks[Sinks] sections of the documentation. 

Don't see what you're looking for? Create a link:Creating-Custom-Modules[custom module] (and then consider link:Contribute[contributing] it back to Spring XD). 

Want to add some analytics to your stream? Check out the link:Taps[Taps] and link:Analytics[Analytics] sections. 